# Use Node LTS image
FROM node:20

# Set working directory
WORKDIR /app

# Copy package files and install
COPY package*.json ./
RUN npm install

# Copy all source files
COPY . .

# Expose the port
EXPOSE 8000

# Start the app
CMD ["npm", "start"]
